# Generated by Django 4.0.4 on 2022-05-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_home_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='abou',
        ),
    ]
