# Generated by Django 4.0.4 on 2022-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_about_abou'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
